### ISSUE TITLE
[v1.0.0] ANSI color codes not supported by windows standard command line

### ISSUE THREAD

**Issue by BlueAndi** [NewTec-GmbH/pyJiraCli#11]
![image](https://github.com/NewTec-GmbH/pyJiraCli/assets/9699465/e729f136-13b0-4172-953c-f857ff3d57a5)

**Comment by Timuuc** [comment]
which commandline was used? cmd and powershell seem to be working fine

**Comment by BlueAndi** [comment]
I am using the cmd.exe ... be aware that not all windows versions of the cmd support ANSI color codes.

**Comment by BlueAndi** [comment]
BTW the Colorama library is missing in the setup.cfg.

**Comment by BlueAndi** [comment]
BTW just_fix_windows_console() is not called!
