### ISSUE TITLE
Command to list the profiles

### ISSUE THREAD

**Issue by BlueAndi** [NewTec-GmbH/pyJiraCli#110]
Add a command which lists all stored profiles, This helps using the tool after while again.

**Comment by gabryelreyes** [comment]
This feature requires a huge rework of the architecture. To the point that it can only be released in a v3 of the tool.

It lies mainly on the fact the profile actions are currently dependent on reaching the JIRA server, however listing the servers does not specifiy a server and therefore the application closes with an error before event looking at the profiles.
