### ISSUE TITLE
add functionalities to initialize a new project from a project.json file

### ISSUE THREAD

**Issue by Timuuc** [NewTec-GmbH/pyJiraCli#22]
Add the capability that the tool can read in a project file. The file must contain a project key for the new project. The file may contain multiple issues which will be created in the neew project. The file may contain links for the issues to be connected (Task - Sub-Tasks)

**Comment by gabryelreyes** [comment]
A project is not created by the file. The project is created manually by the Jira admin, and the initial issues are created by pyJiraCli
