### ISSUE TITLE
improve server url handling

### ISSUE THREAD

**Issue by Timuuc** [NewTec-GmbH/pyJiraCli#23]
In the current version two server urls can be stored (default and server). If both urls are stored the tool will always use the "server" url. 
It should be possible to switch between urls with a command or specify which url is to be used with the current command. ( maybe server_1 and server_2 )
If the generic config for issue fields is implemented, the config must always be according to which url is in use
Login data must be server specific, this could be solved by adding profiles for each server.

The profile must contain:
- the server url
- a configuration file for this jira instance (see issue #2)

The profile might also contain:
- login data for this server
- a server certificate

**Comment by gabryelreyes** [comment]
Profile __folder__ can also contain the server field configuration, data, schemas, etc. Not encrypted.

**Comment by Timuuc** [comment]
with the server profiles the encryption module will be removed. The api token will be stored in plain text until a better solution is found. Username and password will not be stored anymore but must be provided on the commandline any time the tool is used 
(if no token is available in the server profile).

**Comment by Timuuc** [comment]
this issue adresses the same objective as #32. 
#32 was closed for this reason
