### ISSUE TITLE
Command arguments

### ISSUE THREAD

**Issue by gabryelreyes** [NewTec-GmbH/pyJiraCli#25]
- Arguments that are longer than one character must be prefixed by `--`. Example: `--version`
- Arguments that are exactly one character must be prefixed by `-`. Example: `-v`

This must be checked for all commands

**Comment by Timuuc** [comment]
for some argument groups like "expiration" we can add a mutually_exclusive_argument_group(required=false). This will ensure that only one or none of the arguments in the group will be accepted by argparse
