### ISSUE TITLE
develop test concept for pyJiraCli 

### ISSUE THREAD

**Issue by Timuuc** [NewTec-GmbH/pyJiraCli#28]
Develop a test concept for the pyJiraCli tool.
The concept should cover which tests need to be written in the repositiory and the Actions which will be processed when pushing to a branch. 
Explore GitHub possibilities to connect to a demo-attlassian server to test the commands provided by pyJiraCli.

**Comment by gabryelreyes** [comment]
Blocked by #36

**Comment by gabryelreyes** [comment]
Blocked by #68

**Comment by gabryelreyes** [comment]
Must create a board with sprints using the Jira API to be able to test the sprint command.
