### ISSUE TITLE
Update the function descriptions.

### ISSUE THREAD

**Issue by BlueAndi** [NewTec-GmbH/pyJiraCli#4]
Please update the function descriptions:
* Use complete sentences.
* Add the datatypes.
* Describe all function arguments.

Recommended for VSCode the extension "autoDocstring - Python Docstring Generator". This supports in creating function descriptions.

**Comment by Timuuc** [comment]
Fixed with commit 99af7426f11bffac690326c25b1be9bc7d1517f6 on branch fix-issue-4
