### ISSUE TITLE
add sprints command

### ISSUE THREAD

**Issue by Timuuc** [NewTec-GmbH/pyJiraCli#57]
- [ ] add sprints command module
- [ ] add functionality to search for sprints in a board
- [ ] save found sprints in a JSON file

**Comment by gabryelreyes** [comment]
Is this not achieved using JQL?

**Comment by Timuuc** [comment]
No because using JQL you only get the data contained in the issues the search returns. For sprints there is sprint specific data that needs to be written into a JSON file. To not overcrowd the export command, this new command will be added in version 2.1.0.
The version will take a jira board name as input and print all infos to the associated sprints into a JSON file. The sprint data will not be parsed and therefore the command will work generically.
