### ISSUE TITLE
Tool review for v2.0.0

### ISSUE THREAD

**Issue by Timuuc** [NewTec-GmbH/pyJiraCli#63]
A review of the tool is needed before relasing version v2.0.0

**Comment by BlueAndi** [comment]
Typo:
``` -h, --help            show this help message and exit```

Please a complete sentence.

**Comment by gabryelreyes** [comment]
> Typo: ` -h, --help show this help message and exit`
> 
> Please a complete sentence.

@BlueAndi This text is automatically generated by Argparse, given that it is a default option. So we cannot change the text
