### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by Timuuc** [NewTec-GmbH/pyJiraCli#92]

**Comment by gabryelreyes** [comment]
Closed by #91

**Comment by Timuuc** [comment]
The JSON example is not up to date, remove cryptography from Used libraries

**Comment by gabryelreyes** [comment]
@Timuuc 
- If cryptography is not longer used, please also remove it from the `pyproject.toml`
- You know how the latest version of the JSON example looks like, as it is part of the export and search commands.
